### ISSUE TITLE
v2.0.0-rc6: unable to get video stream via bticino_ha_extras plugin

### ISSUE THREAD

**Issue by marcob79** [k-the-hidden-hero/bticino_intercom#46]
Hi,
I'm having a try to your wonderful work in v2.0.0-rc6
I made a ring at about 18:51 after setting up also a dashboard that leverage on bticino_ha_extras.
It look like the plugin correctly shows ring event and the size become bigger.
hoever no image is displayed
moreover, as soon as I try to answer, i got an error like:
'SignalingClient' object has no attribute 'ensure_connected'

logs attached

let me know if you need further info or i can help you with some further checks/tests

thanks

[home-assistant_2026-04-22T16-54-03.660Z.zip](https://github.com/user-attachments/files/26978955/home-assistant_2026-04-22T16-54-03.660Z.zip)

**Comment by thekoma** [comment]
Fixed in **v1.9.6** — the issue was that `ensure_connected()` and `resubscribe()` were added to pybticino after the v1.7.2 release, so they weren't available on PyPI.

**What changed:**
- Released **pybticino v1.8.0** on PyPI (includes the missing methods)
- Released **bticino_intercom v1.9.6** which requires `pybticino>=1.8.0`

To update: HACS → check for updates → reinstall → restart HA.

Thanks for the report!
